### ISSUE TITLE
GTK4 w/o X11

### ISSUE THREAD

**Issue by concatime** [fcitx/fcitx5-gtk#11]
Hi, looking at CMakeLists.txt, it seems that X11 is a hard dependency. Can you provide a way to compile GTK4 feature w/o X11? Aka with wayland instead? That would be awesome.
Thank you.

**Comment by wengxt** [comment]
Can you try the fix and see if it works?

**Comment by concatime** [comment]
Thank you for quickly diving in.
It does not work yet:
```
/build/fcitx5-gtk-c1323ce22f97540bc8b1f1426e6f98ff687a04da/gtk4/fcitximcontext.cpp:27:10: fatal error: 'xcb/xcb.h' file not found
#include <xcb/xcb.h>
         ^~~~~~~~~~~
1 error generated.
```
`libxcb` should only be used in an X11 environment.

**Comment by wengxt** [comment]
Thanks, actually I didn't realize that I accidentally include that file.. it was not used anyway.

Can you try again?

**Comment by concatime** [comment]
Can you merge https://github.com/fcitx/fcitx5-gtk/pull/12 too, this way I can try master directly and not my own fork?

**Comment by concatime** [comment]
All I can say for now is that it compiles successfully. Thank you :tada:
