### ISSUE TITLE
[GTK3 only] Gtk3InputWindow::Init() does not correctly setup candidate window's GdkScreen which can crash gdk_window_set_transient_for()

### ISSUE THREAD

**Issue by willyywt** [fcitx/fcitx5-gtk#15]
Currently `Gtk3InputWindow::Init()` use default constructor `gtk_window_new()` to create the candidate window and directly pass it to `gdk_window_set_transient_for(gdkWindow, parent_)`.

However, `parent_` can somehow use a non-default `GdkScreen`, for example by using `gtk_window_set_screen()` or using `gdk_wayland_window_set_transient_for_exported()`. This can make `gdk_window_set_transient_for()` crashes on `GDK_BACKEND=wayland` with the following assertion message:
```
xdg-desktop-portal-gtk: Gdk:ERROR:../gdk/wayland/gdkwindow-wayland.c:4121:gdk_wayland_window_set_transient_for: assertion failed: (parent == NULL || gdk_window_get_display (window) == gdk_window_get_display (parent))
xdg-desktop-portal-gtk: Bail out! Gdk:ERROR:../gdk/wayland/gdkwindow-wayland.c:4121:gdk_wayland_window_set_transient_for: assertion failed: (parent == NULL || gdk_window_get_display (window) == gdk_window_get_display (parent))
```

On `GDK_BACKEND=x11` GTK use `XSetTransientForHint()` but ignore it's failure, so errors do not lead to a crash, but transition window can not succeed anyway.

**Comment by willyywt** [comment]
Pull Request #16

**Comment by willyywt** [comment]
鉴于GTK4直接去掉了`GdkScreen`([stop-using-gdkscreen](https://docs.gtk.org/gtk4/migrating-3to4.html#stop-using-gdkscreen))，fcitx5在GTK4用`gdk_surface_new_popup(surface, false)` 创建candidate window，应该不会遇到类似的问题

**Comment by willyywt** [comment]
最典型的例子肯定是xdg-desktop-portal-gtk，因为xdg-desktop-portal-gtk本身是在host上运行，但是它会尝试利用xdg-foreign获取一个handle（比如[filechooser.c#L471](https://github.com/flatpak/xdg-desktop-portal-gtk/blob/1.12.0/src/filechooser.c#L471)，[print.c#L485](https://github.com/flatpak/xdg-desktop-portal-gtk/blob/2ea8803d97ec4e0bb9d51b35c6ae522d27d6a79a/src/print.c#L485)等等），这个handle是由flatpak里面传进来的（X11传进来一个xid，Wayland传进来特殊string以后被compositor处理得到client_area），我见到的Qt程序传诸如"x11:1"之类的然后直接挂掉，然后xdg-desktop-portal-gtk自己创建一个，但是GTK程序很不幸通常都能传一个正确的handle，而这个handle对应的client_area对应的GdkScreen肯定不是host上面的GdkScreen

我之前一直以为问题只存在在flatpak，但是后来尝试在正常环境下也能复现，所以我估计是fcitx的问题

**Comment by wengxt** [comment]
怎么复现

Willy (Yang Wentao) ***@***.***>于2022年2月9日 周三08:01写道：

**Comment by willyywt** [comment]
在GTK的官方例子[tests/testtextview.c](https://gitlab.gnome.org/GNOME/gtk/-/blob/3.24.31/tests/testtextview.c)的基础上稍作改动，把widget移到非默认的GdkScreen上面即可复现此bug，以下是一个patch
```
diff --git a/testtextview.c~ b/testtextview.c
index 0cfd0a1..fba5c67 100644
--- a/testtextview.c~
+++ b/testtextview.c
@@ -1,7 +1,6 @@
-
-
-#include "config.h"
 #include <gtk/gtk.h>
+#include <gdk/gdkwayland.h>
+#include <glib.h>
 
 typedef struct {
   GtkTextView parent;
@@ -229,6 +228,17 @@ main (int argc, char **argv)
   gtk_text_view_add_child_at_anchor (GTK_TEXT_VIEW (textview),
                                      button2, anchor);
 
+  if (!GDK_IS_WAYLAND_DISPLAY(gdk_display_get_default())) {
+    g_message("Not running on wayland, XSetTransientForHint() will fail but this is not fatal");
+  } else {
+    g_message("Running on wayland, gdk_wayland_window_set_transient_for will g_assert() and crash");
+  }
+  const char *fake_display_id = g_getenv("FAKE_DISPLAY");
+  GdkDisplay *fake_display = gdk_display_open(fake_display_id);
+  GdkScreen *fake_screen = gdk_display_get_default_screen(fake_display);
+  gtk_window_set_screen(GTK_WINDOW(window), fake_screen);
+  g_print("Is default screen: %s\n", gdk_screen_get_default() == fake_screen ? "YES" : "NO");
+
   gtk_widget_show (window);
 
   gtk_main ();
```
编译：
```
gcc `pkg-config --cflags gtk+-3.0` -o testtextview testtextview.c `pkg-config --libs gtk+-3.0`
```
用testfilechooser.c等等也可以复现类似的的问题，只要加上一段gtk_window_set_screen()

**Comment by wengxt** [comment]
我能理解你的例子为什么能触发

但我有两个问题，
1、为什么 xdg portal gtk会触发，你指出的api在gtk内部没有修改display的操作
2、为什么不用set display而用set screen

Willy (Yang Wentao) ***@***.***>于2022年2月9日 周三08:05写道：

**Comment by willyywt** [comment]
第二个问题我不懂，我猜set_screen是可以的，至于更加正确的的是不是set_display就不知道了
第一个问题确实gdk_wayland_window_set_transient_for_exported()内部不在gtk内部修改display，但是利用了zxdg_imported_v1_add_listener()和zxdg_imported_v1_set_parent_of()修改wl_surface

**Comment by wengxt** [comment]
后两者只是在wl 协议的基础上发送消息给compositor，并没有将它移动到别的display

**Comment by wengxt** [comment]
读了一下 xdg-desktop-portal-gtk 的代码，重要的看起来是 external window 都是采用了全新的 gdk_display_open，当然，这也是可以理解的，因为它需要同时支持来自 wayland 和 xwayland 的窗口，而导致 gdk_display_get_default 并不会是这这两个窗口相同的窗口。
