### ISSUE TITLE
Consolidating the project license information

### ISSUE THREAD

**Issue by hosiet** [fcitx/fcitx5-gtk#2]
I have read through the code and found that there is not a project-level license information available. For the source code, some of the source files have GPL-2.0+ headers while others have LGPL-2.1+ headers. Is it possible to provide a `LICENSE` file so that the overall license information is more clear? Besides, it would be even better if the license across all source files are unified.

Thanks very much in advance!

**Comment by hosiet** [comment]
Ping @wengxt any progress on this issue?

**Comment by wengxt** [comment]
I think this is now fixed after the spdx change.

**Comment by hosiet** [comment]
Thanks, that works.
