### ISSUE TITLE
Text is removed when typing on Youtube

### ISSUE THREAD

**Issue by trmdi** [fcitx/fcitx5-gtk#22]
Step to reproduce:

- Open Firefox
- Go to https://www.youtube.com/
- Type into Youtube's search box: a af (press Enter right after the "f" character without committing it)
- The whole text inside the search box is removed.

**Comment by trmdi** [comment]
This seems to be an issue of the engine, not just fcitx5-unikey because fcitx5-bamboo is also affected.

**Comment by trmdi** [comment]
ibus-unikey doesn't have thís issue.

**Comment by trmdi** [comment]
**Related bug:** when you type "af" in Firefox's address bar and press Enter, it just commits the string without submitting the query to the search egine e.g. Google. In Chrome/Edge... it works as expected with just one Enter pressed.

**Comment by trmdi** [comment]
**Another related bug only happens with Firefox:** when you are in a Xenforo text input, type `:foo` for example to show the emoticon AutoComplete dropdown, if you press an arrow key to select one then press Enter, nothing will be inserted into the text input.

**Comment by trmdi** [comment]
This seems to fix it, though I don't fully understand the root cause, it's mostly a guess.

    diff --git a/src/unikey-im.cpp b/src/unikey-im.cpp
    index 232d686..5e05551 100644
    --- a/src/unikey-im.cpp
    +++ b/src/unikey-im.cpp
    @@ -365,6 +365,11 @@ void UnikeyState::preedit(KeyEvent &keyEvent) {
             (sym >= FcitxKey_Home && sym <= FcitxKey_Insert) ||
             (sym >= FcitxKey_KP_Home && sym <= FcitxKey_KP_Delete)) {
             handleIgnoredKey();
    +
    +        // workaround fcitx/fcitx5-gtk#22
    +        keyEvent.filterAndAccept();
    +        ic_->forwardKey(keyEvent.origKey(), keyEvent.isRelease(), keyEvent.time());
    +
             return;
         } else if (state.test(KeyState::Super)) {
             return;

**Comment by trmdi** [comment]
Friendly ping!

**Comment by zenfas** [comment]
This issue happens on fcitx5-bamboo and fcitx5-m17n (both telex or vni) also

**Comment by zenfas** [comment]
Another removed issue is switch input method on fcitx5-android using unikey
Mr Rocket Aaron told me it relate code of fcitx5-unikey https://github.com/fcitx/fcitx5-unikey/blob/5.0.11/src/unikey-im.cpp#L134-L136

Instead of keep current text when switching input method, it delete it
![Screenshot_2022-11-07-22-05-09-033_org telegram messenger web](https://user-images.githubusercontent.com/66258788/200344730-1c22c14e-9b65-453c-880c-e85b5c3c4973.jpg)

Can you help us check it @wengxt , any relate to this topic issue also.
Thank you

**Comment by trmdi** [comment]
@zenfas https://github.com/fcitx/fcitx5-unikey/pull/27
That issue is not related to this one, next time please make a new issue.

**Comment by trmdi** [comment]
> This seems to fix it, though I don't fully understand the root cause, it's mostly a guess.
> 
> ```
> diff --git a/src/unikey-im.cpp b/src/unikey-im.cpp
> index 232d686..5e05551 100644
> --- a/src/unikey-im.cpp
> +++ b/src/unikey-im.cpp
> @@ -365,6 +365,11 @@ void UnikeyState::preedit(KeyEvent &keyEvent) {
>          (sym >= FcitxKey_Home && sym <= FcitxKey_Insert) ||
>          (sym >= FcitxKey_KP_Home && sym <= FcitxKey_KP_Delete)) {
>          handleIgnoredKey();
> +
> +        // workaround fcitx/fcitx5-gtk#22
> +        keyEvent.filterAndAccept();
> +        ic_->forwardKey(keyEvent.origKey(), keyEvent.isRelease(), keyEvent.time());
> +
>          return;
>      } else if (state.test(KeyState::Super)) {
>          return;
> ```

not a true fix but maybe it's a clue? @wengxt

**Comment by wengxt** [comment]
Please report the bug to firefox.

**Comment by trmdi** [comment]
> Please report the bug to firefox.

I'm not sure if it's a firefox's bug because ibus doesn't have this bug. If you're sure then I will do that.

**Comment by wengxt** [comment]
most likely it's a youtube's js bug, but no one can change the website.

Also obviously chrome can't trigger such bug.

**Comment by wengxt** [comment]
but if ibus can't trigger it , there should be some way to workaround it.

**Comment by trmdi** [comment]
> but if ibus can't trigger it , there should be some way to workaround it.

Workaround I posted above works fine. I just don't fully understand how it works behind the scene.

**Comment by wengxt** [comment]
Move to fcitx5-gtk, interestingly, even when using GTK_IM_MODULE=ibus with firefox and fcitx5, this issue doesn't happen, which means there should be a way to change fcitx5-gtk to make it work

**Comment by trmdi** [comment]
Thank you, it works perfectly. Will you bump the version soon? I ask to make a decision to backport the fix to my distro or not.
Same question for unikey.
