### ISSUE TITLE
Does not work if 32-bit gtk2 version is installed

### ISSUE THREAD

**Issue by Xandaros** [fcitx/fcitx5-gtk#6]
At least on Arch Linux, if you have both `gtk2` and `lib32-gtk2` installed, it refuses to work in at least Discord.

`fcitx5-diagnose` kept insisting that the GTK2 module was not found, while `gtk-query-immodules-2.0` listed it. Eventually I noticed that it wasn't actually using `gtk-query-immodules-2.0`, but `gtk-query-immodules-2.0-33`, which is a 32-bit executable and appears to be the same thing used for the 32 bit version of GTK2.
After uninstalling lib32-gtk2, I could switch input method in Discord and finally type in Japanese again.

**Comment by wengxt** [comment]
I don't think it's really relevant to what fcitx5-diagnose outputs. fcitx5-diagnose is just a script and even if it print something false positive, it won't affect the actual program.

Also if you want fcitx5-gtk to work with lib32-gtk{2,3}, you need to ask packager to build lib32-fcitx5-gtk and that's certainly do-able.

Finally, I don't know why lib32-gtk2 is relevant to discord. Arch's discord is using Gtk3. And I have lib32-gtk2 installed and it doesn't affect anything between fcitx/discord.
$ ldd /opt/discord/Discord | grep gtk
        libgtk-3.so.0 => /usr/lib/libgtk-3.so.0 (0x00007f4870e31000)

I'd only guess that your "discord" might be something especial, or you misunderstood the actual behavior you found.
